# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-28 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='AddStock',
        ),
        migrations.RenameField(
            model_name='earnings',
            old_name='stock_earnings',
            new_name='earnings',
        ),
    ]
